### ISSUE TITLE
Feature suggestion: Accept word list from standard input (to allow piping)

### ISSUE THREAD

**Issue by bwbug** [sts10/tidy#12] opened 2022-08-07 16:18 UTC
Not sure if there are limitations that would prevent this from being implementable, but it would be nice to be able to use pipes to supply the input word list, for example as follows:

`tidy -in wordlist.txt | tidy -L -A --dry-run`

This would allow better control over the sequence of operations, without requiring the user to save an intermediate result.

**Comment by sts10** [comment] 2022-08-07 18:30
Yep, this has been on my list, but I've had trouble figuring out how this works with Rust command-line tools. If anyone is reading this and can help please provide tips or a Pull Request!

**Comment by sts10** [comment] 2022-08-16 22:31
Was playing around with this and discovered something. 

We can run 
```shell
tidy -m 5 word_list.txt > tidy -M 5 -o outputted_list.txt
```

which results in a new file called `outputted_list.txt` that only has 5 character words. 

Likewise we if we switch the `|` to a `>` in your example to make `tidy -in eff.txt > tidy -L -A --dry-run`, it seems to run as intended. 

As I've implied, I'm not an expert on command-line piping, so I would understand if there's some functionality that "pipe-ability" has that is lost with `>`. But I'm glad there's at least one way to combine tidy with other commands, including itself.

**Comment by sts10** [comment] 2023-01-20 05:02
Gonna close this for now, as I think Mac/Linux users can pipe sufficiently well. Unfortunately, without a Windows machine available to me, it's hard for me to support it fully/when Windows differs in functionality.

**Closed by sts10** 2023-01-20 05:02 UTC
Labels: enhancement, help wanted
